# Generated by Django 4.1 on 2026-02-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Внутренний ID')),
                ('instagram_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID поста в Instagram')),
                ('caption', models.TextField(blank=True, verbose_name='Текст поста (описание)')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Количество лайков')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Количество комментариев')),
                ('media_url', models.URLField(max_length=1000, verbose_name='Ссылка на медиафайл (CDN)')),
                ('permalink', models.URLField(max_length=1000, verbose_name='Постоянная ссылка')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='Дата публикации в Instagram')),
                ('media_type', models.CharField(max_length=50, verbose_name='Тип медиа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки в базу')),
            ],
        ),
    ]
